### ISSUE TITLE
New Cursor Rules

### ISSUE THREAD

**Issue by barsketis** [haydenbleasel/next-forge#454]
**Is your feature request related to a problem? Please describe.**
Adding in more robust cursor rules will help beginner developers use this repo. Due to its size, its hard for cursor to keep context and we could provide simple rules that tell cursor how to properly utilize each package.

Cursor has implemented a new cursor rules system, that moves away from the .cursorrules file and might be a good fit for this project.
[Cursor Rules Update](https://www.cursor.com/changelog/-cursor-rules-better-codebase-understanding-new-tab-model)

**Describe the solution you'd like**
 I suggest implementing smaller cursor rules that are referenced based on the file context or package being utilized. Im not too sure how cursor is parsing these as they havent given any examples yet, however here is the structure I think would work well to start.

I was thinking of having 1 default rule that gives a basic overview of the project, then implement one of the 8 rules below based on the user prompt to cursor, or based on the file path or imports of the file.

```
### General Structure - Default Rule
- Project File Structure
- Tech Stack
- DB Design
- Global Design variables
- Functions Available, @ the files, and @ the docs related to each packages below

### Analytics Management
- add_web_analytics  
- add_product_analytics  
- track_pageview  
- track_event  
- set_user_id  

### Authentication & Security
- add_authentication  
- login  
- logout  
- register_user  
- validate_token  
- set_security_policy  
- add_rate_limiting  
- scan_dependencies  
- set_security_headers  
- lookup_ip  

### Content Management (CMS)
- add_page  
- update_page  
- delete_page  
- fetch_page  
- list_pages  

### Database Operations
- connect_database  
- disconnect_database  
- execute_query  
- insert_record  
- update_record  
- delete_record  

### Design System Customization
- add_component  
- update_component  
- delete_component  
- list_components  
- set_primary_color  
- set_secondary_color  
- apply_theme  
- set_font_family  
- set_font_size  
- set_font_weight  

### Automation & Scheduling
- add_cron_job  
- cancel_cron_job  
- list_cron_jobs  
- run_cron_job  

### Observability & Debugging
- add_error_capture  
- list_errors  
- clear_errors  
- start_debug_session  
- stop_debug_session  
- capture_debug_snapshot  
- record_log  
- fetch_logs  
- clear_logs  
- monitor_uptime  
- get_uptime_status  
- set_uptime_alert  

### Integration & Communication
- send_email  
- preview_email  
- send_notification  
- schedule_notification  
- cancel_notification  
- register_webhook  
- trigger_webhook  
- list_webhooks  
- process_payment  
- refund_payment  
- list_payments  
- get_payment_status  
- create_collaboration_session  
- join_collaboration_session  
- leave_collaboration_session  
- send_collaboration_message  
- share_collaboration_file
```

I have some sample rules I am still testing based on this users recommendations
https://forum.cursor.com/t/my-best-practices-for-mdc-rules-and-troubleshooting/50526

For example
```
name: "009-Integration-Communication"
version: "1.0"
triggers:
  - file_change
match:
  anyPath:
    - "packages/payments/**/*"
    - "packages/webhooks/**/*"
    - "packages/storage/**/*"
    - "packages/formatting/**/*"
    - "packages/collaboration/**/*"
    - "packages/email/**/*"
    - "packages/notifications/**/*"
  anyExtension: [".ts", ".tsx"]
  containsRegex:
    - "@repo/(payments|webhooks|storage|formatting|collaboration|email|notifications)"
---
```yaml
rule_definition:
  description: >
    Covers various integration or communication packages: 
    payments, webhooks, storage, formatting, collaboration, email, notifications.

  rules:
    - name: payments-usage
      severity: "error"
      details: >
        `payments.charge --amount=... --currency=... --source="..." "desc"`, 
        `payments.refund --transactionId=...`.
      guidance: >
        E.g. `payments.charge --amount=9.99 --currency="USD" --source="tok_abc" "Order #12"`

    - name: webhooks-commands
      severity: "info"
      details: >
        `webhooks.register --url="..." [--event="..."]`, 
        `webhooks.trigger --event="..." [--data="JSON"]`.
      guidance: >
        E.g. `webhooks.register --url="https://myapp.com/hook" --event="order.shipped"`

    - name: storage-commands
      severity: "warning"
      details: >
        `storage.upload --bucket="..." --file="..." [--key="..."]`, etc. Must quote strings.
      guidance: >
        E.g. `storage.download --bucket="my-bucket" --key="myfile" --destination="localfile"`

    - name: formatting-usage
      severity: "info"
      details: >
        `format.apply --style="..." "text"`, `format.clear "text"`, `format.preview --style="..." "text"`.
      guidance: >
        E.g. `format.apply --style="uppercase" "hello world"`

    - name: collaboration-usage
      severity: "info"
      details: >
        `collaboration.createSession "sessionName"`, `collaboration.shareFile --id="..." "path"`, etc.
      guidance: >
        E.g. `collaboration.sendMessage --id="123" "Hello Team"`

    - name: email-notifications
      severity: "warning"
      details: >
        If referencing `email.send --to="..." --subject="..." "body"` or 
        `notifications.send --channel=... --to="..." "message"`.
      guidance: >
        E.g. `notifications.send --channel=email --to="user@domain.com" "Hey!"`
```

**Describe alternatives you've considered**
Alternatively, we could have a rule for each App in the /apps folder, then a rule for each /packages router.

I will work on adding these basic 9 rules to start to see how cursor performs on the project with them. If anyone has any suggestions, or knowledge on how to best structure cursor rules for a turbo repo, let me know.
